### ISSUE TITLE
Verify dimensions of mfdataset match weight table

### ISSUE THREAD

**Issue by rileyhales** [geoglows/rapid-inflows#5]
There should be a way to check that the dimensions of the weight table match the dimensions the weight table was generated for. May need additional arguments to the function, a naming convention for the csvs, etc. Whatever you decide to do should have documentation given in the readme and docstrings

**Comment by RickytheGuy** [comment]
I'm not sure quite what you mean by that first sentence. are you talking about how the weight table names contain the dimensions of the input runoff datasets?

**Comment by rileyhales** [comment]
No the dimensions of the arrays. The weight table name contains the resolution of the grid it was generated from. the size of the array that xarray gets should be the same.
